# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#######################################

[[main]]
  name = "About"
  url = "#about"
  weight = 1

[[main]]
  name = "CV"
  url = "pdf/CV.pdf"
  weight = 2

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 3

[[main]]
  name = "Articles"
  url = "#featured"
  weight = 4

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 5

#######################################

[[main]]
  identifier = "Personal"
  name = "Personal"
  weight = 30

[[main]]
  parent = "Personal"
  name = "Music"
  url = "personal/music"

[[main]]
  parent = "Personal"
  name = "Art"
  url = "personal/art"

[[main]]
  parent = "Personal"
  name = "Travel"
  url = "personal/travel"

[[main]]
  parent = "Personal"
  name = "Food"
  url = "personal/food"

#######################################

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100



# [[main]]
#   parent = "frand"
#   name = "adidas"
#   url = "/frands/adidas/"
#
# [[main.frands]]
#   name = "frand1"
#   url = "/frands/"
#   weight = 2
#
# [[main.brands]]
#   name = "frand2"
#   url = "/frands/"
#   weight = 3
