# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Home"
  url = "#about"
  weight = 10

# Link to a PDF of your CV from the menu.
# To enable, copy your CV to `static/pdf/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "pdf/CV.pdf"
   weight = 12

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 15

[[main]]
  name = "Math Articles"
  url = "#math-articles"
  weight = 20

[[main]]
  name = "Accomplishments"
  url = "#accomplishments"
  weight = 25


[[main]]
  name = "Posts"
  url = "#posts"
  weight = 30

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 35

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Personal"
  url = "www.google.com"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100


[[menu.main]]
  identifier = "brand"
  name = "brand"
  url = "/brands/"

[[menu.main]]
  parent = "brand"
  name = "nike"
  url = "/brands/nike/"

[[menu.main]]
  parent = "brand"
  name = "adidas"
  url = "/brands/adidas/"

[[menu.main.brands]]
  name = "brand1"
  url = "/brands/"
  weight = 2

[[menu.main.brands]]
  name = "brand2"
  url = "/brands/"
  weight = 3
