# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#######################################

[[main]]
  name = "About"
  url = "#about"
  weight = 1

[[main]]
  name = "CV"
  url = "pdf/CV.pdf"
  weight = 2

[[main]]
name = "Papers"
url = "#papers"
weight = 3

[[main]]
name = "More Math/Stat/Sports"
url = "#more_math_stat_sports"
weight = 4


[[main]]
name = "Teaching"
url = "#teaching"
weight = 5


# [[main]]
#   name = "Math Blog"
#   url = "#math"
#   weight = 4

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 5

# [[main]]
#   name = "Photos"
#   url = "#photos"
#   weight = 6



[[main]]
  name = "Contact"
  url = "#contact"
  weight = 10

#######################################

# [[main]]
#   identifier = "Personal"
#   name = "Personal"
#   weight = 30
#
# [[main]]
#   parent = "Personal"
#   name = "calhat"
#   url = "/calhat/"
#   weight = 10
#
# [[main]]
#   parent = "Personal"
#   name = "Art"
#   url = "/art/"
#   weight = 20
#
# [[main]]
#   parent = "Personal"
#   name = "Music"
#   url = "/music/"
#   weight = 30
#
# # [[main]]
# #   parent = "Personal"
# #   name = "Travel"
# #   url = "/travel/"
# #   weight = 40
#
# [[main]]
#   parent = "Personal"
#   name = "Food"
#    #pre = "<i class='fa fa-heart'></i>"
#    url = "/food/"
#    weight = 50


#######################################
