---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
theme_set(theme_bw())
theme_update(text = element_text(size=18))
theme_update(plot.title = element_text(hjust = 0.5))
```

# [Bet, Sweat, and Forget.](https://open.spotify.com/show/1bABVhkwnd3sDaBSZLC0oY)

#### Each week during the NFL season, Ryan Brill and Nick Miller make $50 worth of NFL bets on the [Bet, Sweat, and Forget](https://open.spotify.com/show/1bABVhkwnd3sDaBSZLC0oY) podcast, competing for glory and the title of "best bettor". 

## 2023 NFL Season.


```{r, echo=FALSE, warning=FALSE, fig.align = "center",fig.width=8.5, fig.height=5}
# out.width = "85%"
nick <- c(0,0,-21.36,-32.75,-7.16,0.68,-9.32,-59.32,-16.39,-18.66,7.71,7.71,7.71)
ryan <- c(0,0,-2.27,11.37,57.91,103.37,77.44,27.44,41.08,54.72,88.80,88.80,88.80)
guest_profits <- c(NA,NA,NA,NA,NA,13.63,NA,-50,-6.36,-50,NA,NA,NA)
guest_names <- c(NA,NA,NA,NA,NA,"Frank",NA,"Kole","Harry","Jake",NA,NA,NA)
guest_weeks <- c(0,1,2,3,4,5,6,7,8,9,10,11,12)

N = length(ryan)
num_weeks <- 0:(N-1)
df <- data.frame(nick, ryan, num_weeks)

df_guests <- data.frame(guest_profits, guest_names, guest_weeks)

COLORS <- c("Nick" = "firebrick", 
            "Ryan" = "dodgerblue2",
            "Zero" = "gray50",
            "Guest" = "gray25")

ggplot(data = df) +

geom_line(aes(x = df$num_weeks, y = rep(0, N), color = "Zero"), lwd=.4) +
geom_line(aes(x = df$num_weeks, y = df$nick, color = "Nick"), lwd=1.3) +
geom_line(aes(x = df$num_weeks, y = df$ryan, color = "Ryan"), lwd=1.3) +
geom_point(data = df_guests, aes(x= df_guests$guest_weeks,
                                 y = df_guests$guest_profits,
                                 color = "Guest")) +
geom_text(data = df_guests, aes(x= df_guests$guest_weeks,
                                y = df_guests$guest_profits,
                                label=guest_names,
                                color = "Guest"),
          hjust=0, vjust=0) +
  scale_color_manual(values=COLORS, name="") +
labs(title = "Bet, Sweat, and Forget 2023 NFL Betting Results", x = "NFL Week Number", y = "Cumulative Profit, USD", color="") +
scale_x_continuous(breaks = num_weeks) +
scale_y_continuous(breaks = seq(-1000,1000,by=20)) +
expand_limits(x = N, y = 0)
```

#### View our weekly bets, and the detailed accounting, [here.](https://docs.google.com/spreadsheets/d/1HXQggSt-OX9teZWsathk3cpLL4cJ3vNu6FosqiM--AE/edit?usp=sharing)

#### View previous seasons of the Bet, Sweat, and Forget Podcast:

* [BSF 2022](/bsf/bsf_2022)
* [BSF 2021](/bsf/bsf_2021)
* [BSF 2020 and 2019](/bsf/bsf_2020_2019)

